name: Deploy Staging
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'screenshots/**'

jobs:
  publish:
    name: Install and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          username: cheeaun
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm
      - run: npm ci
      - env:
          EXPO_APPLE_ID: ${{ secrets.EXPO_APPLE_ID }}
          EXPO_APPLE_TEAM_ID: ${{ secrets.EXPO_APPLE_TEAM_ID }}
          EXPO_ASC_APP_ID: ${{ secrets.EXPO_ASC_APP_ID }}
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}
        run: npm run deploy-staging
