name: Expo Publish
on:
  push:
    branches: [main]

jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@5.3.1
        with:
          expo-username: cheeaun
          expo-version: 3.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-packager: npm
          expo-cache: true
      - run: npm i
      - run: expo publish
